stages:

  data_ingestion:
    cmd: python project/pipeline/1_data_ingestion_pipeline.py
    deps:
      - project/pipeline/1_data_ingestion_pipeline.py
      - project/components/data_ingestion.py
      - yamlfile/config.yaml
    outs:
      - artifacts/data_ingestion/kidney-ct-scan-image

  prepare_base_model:
    cmd: python project/pipeline/2_prepare_basemodel.py
    deps:
      - project/pipeline/2_prepare_basemodel.py
      - project/components/prepare_basemodel.py
      - yamlfile/config.yaml
    params:
      - yamlfile/param.yaml: [IMAGE_SIZE, WEIGHTS, INCLUDETOP, CLASSICS, LEARNING_RATE]
    outs:
      - artifacts/prepare_base_model/vgg16.h5
      - artifacts/prepare_base_model/update_base_mode.h5

  prepare_callbacks:
    cmd: python project/pipeline/3_callbacks.py
    deps:
      - project/pipeline/3_callbacks.py
      - project/components/callbacks.py
      - project/entity/config.py
      - yamlfile/config.yaml
      
    outs:
      - artifacts/prepare_callbacks/tensorboard_log_dir
      - artifacts/prepare_callbacks/checkpoint_

  model_training:
    cmd: python project/pipeline/4_model_training.py
    deps:
      - project/pipeline/4_model_training.py
      - project/components/model_training.py
      - project/components/callbacks.py
      - yamlfile/config.yaml
      - artifacts/prepare_base_model/update_base_mode.h5
      - artifacts/data_ingestion/kidney-ct-scan-image
    params:
      - yamlfile/param.yaml: [LEARNING_RATE, BATCH_SIZE, EPOCHS, AUGMENTATION]
    outs:
      - artifacts/training/model.h5
      

  model_evaluation:
    cmd: python project/pipeline/5_model_evaluation.py
    deps:
      - project/pipeline/5_model_evaluation.py
      - project/components/model_evalution.py
      - project/components/model_training.py
      - yamlfile/config.yaml
      - yamlfile/param.yaml
      - artifacts/training/model.h5
    params:
      - yamlfile/param.yaml: [CLASSICS, IMAGE_SIZE, BATCH_SIZE]
    outs:
      - artifacts/model_evaluation/report/report.json
      - artifacts/model_evaluation/scores/scores.json
      - artifacts/model_evaluation/report.yaml

# stages:
#   full_pipeline:
#     cmd: python project/pipeline/__init__.py
#     deps:
#       - project/pipeline/__init__.py
#       - project/pipeline/training_pipeline.py
#       - project/components/data_ingestion.py
#       - project/components/prepare_basemodel.py
#       - project/components/callbacks.py
#       - project/components/model_training.py
#       - project/components/model_evaluation.py
#       - yamlfile/config.yaml
#     outs:
#       - artifacts/data_ingestion
#       - artifacts/prepare_base_model
#       - artifacts/prepare_callbacks
#       - artifacts/training
#       - artifacts/model_evaluation
    